# Generated by Django 4.1.5 on 2023-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic_by_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Год')),
                ('average_salary', models.CharField(max_length=255, verbose_name='Средняя зарплата')),
                ('average_salary_prof', models.CharField(max_length=255, verbose_name='Средняя зарплата - Backend-программист')),
                ('count_salary', models.CharField(max_length=255, verbose_name='Количество вакансий')),
                ('count_salary_prof', models.CharField(max_length=255, verbose_name='Количество вакансий - Backend-программист')),
            ],
        ),
    ]
