# Generated by Django 4.1.5 on 2023-01-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statistic_by_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic_by_city_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary_count', models.CharField(max_length=255, verbose_name='Доля вакансий')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic_by_city_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('salary_level', models.CharField(max_length=255, verbose_name='Уровень зарплат')),
            ],
        ),
        migrations.RenameModel(
            old_name='Statistic_by_city',
            new_name='Statistic_by_year',
        ),
    ]
