# Generated by Django 4.1.5 on 2023-01-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statistic_by_city_count_statistic_by_city_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Навык')),
            ],
        ),
    ]
