# Generated by Django 4.1.5 on 2023-01-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skills_statistic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills_statistic',
        ),
    ]
